### PR TITLE
Fixes #109: checks for Internet connection in onCreate and onResume

### LINKED ISSUE #109: Display a brief error message on loading page when there is no Internet
Otherwise, people just see a blank screen and don't know what's wrong.

### PR DESCRIPTION
**Pull request by oa2013**
Fixes #109  .

Changes proposed in this pull request:
- Added a method that checks to see if the device is online
- Used this method in both onCreate() and onResume() in LaunchActivity

### CODE REVIEW

File: app/src/main/java/com/tiptopgoodstudio/androidresources/ui/LaunchActivity.java [hunk 1]
```diff
@@ -44,38 +48,67 @@ protected void onCreate(Bundle savedInstanceState) {
...
-            DatabaseReference dbReference = resourceRepository.loadDataFromFirebase();
+        checkConnectivityAndLoadResources();
 
-            dbReference.addListenerForSingleValueEvent(new ValueEventListener() {
+    }
+
+    private void checkConnectivityAndLoadResources() {
+        isOnline = isOnline();
+
+        if(isOnline == true) {
```
Comment (dynamite8) [inline app/src/main/java/com/tiptopgoodstudio/androidresources/ui/LaunchActivity.java]: you can just say if(isOnline)

File: app/src/main/java/com/tiptopgoodstudio/androidresources/ui/LaunchActivity.java [hunk 2]
```diff
@@ -44,38 +48,67 @@ protected void onCreate(Bundle savedInstanceState) {
...
+                    //When we are done with updating data from Firebase, go to MainActivity
+                    @Override
+                    public void onDataChange(DataSnapshot dataSnapshot) {
+                        startMainActivity();
+                    }
 
-                }
-            });
+                    @Override
+                    public void onCancelled(DatabaseError databaseError) {
```
Comment (dynamite8) [inline app/src/main/java/com/tiptopgoodstudio/androidresources/ui/LaunchActivity.java]: why aren't we printing the error here?  Should we remove this method entirely if we're not printing the error?

File: app/src/main/java/com/tiptopgoodstudio/androidresources/ui/LaunchActivity.java [hunk 3]
```diff
@@ -44,38 +48,67 @@ protected void onCreate(Bundle savedInstanceState) {
...
+       checkConnectivityAndLoadResources();
+    }
 
     private void startMainActivity() {
         Intent intent = new Intent(this, MainActivity.class);
         startActivity(intent);
     }
 
+    public boolean isOnline() {
+        ConnectivityManager connMgr = (ConnectivityManager)
```
Comment (dynamite8) [inline app/src/main/java/com/tiptopgoodstudio/androidresources/ui/LaunchActivity.java]: write out connMgr instead of abbreviation

File: app/src/main/java/com/tiptopgoodstudio/androidresources/ui/LaunchActivity.java (hunk 1 above)
Comment (dambadipudi) [reply app/src/main/java/com/tiptopgoodstudio/androidresources/ui/LaunchActivity.java]: So true :)

File: app/src/main/java/com/tiptopgoodstudio/androidresources/ui/LaunchActivity.java (hunk 2 above)
Comment (dambadipudi) [reply app/src/main/java/com/tiptopgoodstudio/androidresources/ui/LaunchActivity.java]: onCancelled means if the Firebase import is cancelled. Isn't it different from the case where the import can't even begin because of no internet connection?

**Comment by oa2013** [comment]
@dynamite8 or @JaeW -- I made requested changes to this PR, please merge.
